### ISSUE TITLE
Mensaje de bienvenida e instrucciones de contribución

### ISSUE THREAD

**Issue by tasugo** [ojoven/odiometro#1]
¿Qué te parece si preparo una PR con un README con instrucciones para poner la aplicación en marcha, pasar los tests y algún que otro link a Express o Jasmine para que cualquiera pueda llegar y ponerse manos a la obra? Eso sí, quizá necesite correcciones porque con Node soy bastante nulo :)

**Comment by ojoven** [comment]
Me parece una idea genial, Manuel.
Dime si quieres que te de algo de información.
¡Gracias!

**Comment by ojoven** [comment]
Hey Manuel,

Ya he creado un README.md decente con instrucciones de instalación.
Si quieres hacer alguna aportación, adelante, pero voy a cerrar ya la issue.

Thanks!

**Comment by tasugo** [comment]
Muchas gracias por esto, y perdón por mi ausencia tras proponer hacerlo yo. No encontré el momento :(
