### ISSUE TITLE
Error al almacenar tweets

### ISSUE THREAD

**Issue by hardcodear** [ojoven/odiometro#9]
Hola, estuve probando el repositorio y note que app.js cae al recibir un error de mysql al almacenar el texto de los tweets.
` code: 'ER_TRUNCATED_WRONG_VALUE_FOR_FIELD',
  errno: 1366,
  sqlMessage: 'Incorrect string value: \'\\xF0\\x9F\\x8E\\xA5Ve...\' for column \'retweeted_text\' at row 1',
  sqlState: '22007',
  index: 0,
  sql: 'INSERT INTO paguero_lookouts.retweets VALUES(null, \'1062998667181862912\', \'Schuma78\', \'🎥Vean esto y difúndanlo, por favor. ¡¡HAY QUE SER MUY MISERABLE!!...\n\n(Ortega Lara) https://t.co/Q7oRHbL4zs\', \' 2018-11-15 21:01:17 \')' }
/home/testmed/domains/lookouts.ohmio.com.ar/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
`
Seguramente un error por algunos caracteres.
en tu server de prueba, que commit es el que esta en producción?

**Comment by Pictor13** [comment]
What's the charset set on the database? That could be the problem.

**Comment by botpartigiano** [comment]
1) Database: Change Database default collation as utf8mb4.
2) Table: Change table collation as CHARACTER SET utf8mb4 COLLATE utf8mb4_bin
https://stackoverflow.com/questions/39463134/how-to-store-emoji-character-in-mysql-database

**Comment by ojoven** [comment]
I'll dump a new version of the database with the character set updated, but botpartigiano got it right.
Cheers to the past! (sorry for the late response!)
